# https://docs.openstack.org/heat/rocky/template_guide/hot_spec.html#hot-spec-template-version
heat_template_version: queens

description: >
  HOT template that invokes subtemplates.

parameters:
  key_name:
    type: string
    description: Name of keypair used to access the compute instance(s).
  public_net_id:
    type: string
    description: ID or name of the public network floating IP addresses are allocated from.
    default: ntnu-internal

resources:
  manager:
    type: manager.yaml
    properties:
      key_name:      { get_param: key_name }
      public_net_id: { get_param: public_net_id }

outputs:
  manager_public_ip:
    description: Public IP address of the manager instance.
    value: { get_attr: [manager, manager_floating_ip] }
